// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecudsfodhnobvlevotdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjdWRzZm9kaG5vYnZsZXZvdGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDM2NjEsImV4cCI6MjA3MTUxOTY2MX0.FEaPUsQwBJZLjD4fonaEd7hA2xBaW5rcqytdFfobrQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});